// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqD9XFrA85WT8TYE8BMAIVXlffMxhTYiA',
    appId: '1:698260294676:web:9fe096d94d7eecc7bd2b01',
    messagingSenderId: '698260294676',
    projectId: 'passa-a-bola-919eb',
    authDomain: 'passa-a-bola-919eb.firebaseapp.com',
    storageBucket: 'passa-a-bola-919eb.firebasestorage.app',
    measurementId: 'G-K1CW9DC3LQ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk8A2n97pKx-4A2d6Szp3uWtSyQzEfL-8',
    appId: '1:698260294676:ios:8e7e6a0da9ad414cbd2b01',
    messagingSenderId: '698260294676',
    projectId: 'passa-a-bola-919eb',
    storageBucket: 'passa-a-bola-919eb.firebasestorage.app',
    iosBundleId: 'com.example.passaabola',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3yxV6tru8VvI3KDYCAm5GdOOrHzMcvUE',
    appId: '1:698260294676:android:0abcc83878bfb499bd2b01',
    messagingSenderId: '698260294676',
    projectId: 'passa-a-bola-919eb',
    storageBucket: 'passa-a-bola-919eb.firebasestorage.app',
  );

}